### ISSUE TITLE
Desktop notification

### ISSUE THREAD

**Issue by joonki34** [joeyespo/inbox-by-gmail-checker#17]
It would be great if this extension supports desktop notification.

**Comment by sahildua2305** [comment]
Desktop notifications for?
Can you elaborate @joonki34

**Comment by joonki34** [comment]
Well I meant the rich notification. It would be nice if the rich notification pops up if a new email has arrived.

**Comment by dkhurshudian** [comment]
[I'm](https://github.com/davo11122/inbox-by-gmail-checker) gonna handle this feature.

**Comment by joeyespo** [comment]
Fixed with #18.

**Comment by joeyespo** [comment]
Just released v4.0.0 which includes this feature. You should see it happening soon. Thanks for opening the issue @joonki34, and for implementing it @davo11122 🎉
