### ISSUE TITLE
Open in current tab if new tab?

### ISSUE THREAD

**Issue by orschiro** [joeyespo/inbox-by-gmail-checker#19]
Dear @joeyespo,

What a great extension. 

Thank you so much!

One request:

Is it possible to open the Inbox in the current tab if the current tab represents a new tab page?

Yours,

Robert

![peek 2017-02-22 17-21-inbox checker](https://cloud.githubusercontent.com/assets/170947/23220857/9031695c-f923-11e6-8ba8-b7bab38d7a27.gif)

**Comment by orschiro** [comment]
Dear @joeyespo,

Can you please merge https://github.com/joeyespo/inbox-by-gmail-checker/pull/20 to address this? :-)

Yours,

Robert

**Comment by joeyespo** [comment]
Excellent! Thanks for the issue and taking this on, @orschiro 😄

**Comment by joeyespo** [comment]
I still haven't seen another extension do this since we last talked in #8 btw. I also personally like it opening in a new tab. So for those reasons, I made this optional and off by default. Feel free to turn it one after upgrading to 4.0.

**Comment by joeyespo** [comment]
Just released v4.0.0 which includes this feature.

Thanks again!

**Comment by orschiro** [comment]
Wow, cool.

Thanks for your quick release.

It's working perfectly with the optional setting. :-)
