### ISSUE TITLE
Setting for update frequency.

### ISSUE THREAD

**Issue by bluMyst** [joeyespo/inbox-by-gmail-checker#2]
Would it be possible to have a setting that changes how frequently the extension updates its unread count?

**Comment by joeyespo** [comment]
Sure!

Not sure when I'll get to this, but I marked this as an enhancement in case anyone out there does it first. Here's the relevant code:
- https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/options.js
- https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/options.html#L24
- https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L12
- https://github.com/joeyespo/inbox-by-gmail-checker/blob/master/background.js#L132

**Comment by joeyespo** [comment]
Implemented by @michliga in #5.
