### ISSUE TITLE
Possible issue: multiple login prompts when not logged in?

### ISSUE THREAD

**Issue by dolan-a** [joeyespo/inbox-by-gmail-checker#29]
I recently signed out of my Google account, and after a short bit of time, a new tab opened with the Google sign in page, where it asks which of my Google accounts to use (I have a few different ones). I clicked on one, then before I could enter my password, a new tab opened asking which account to use.  This process continued over and over, and I couldn't get it to stop until I disabled Inbox Checker.

I don't know for sure if the behavior is from this extension, but the disabling fix makes it seem like it may be. The timing may match with the default `tryAgainTime=5 seconds` time, but again, I'm not familiar enough with this code to know for sure.

If the extension is responsible for this behavior, perhaps the tryAgainTime would be better off incrementing with each retry (e.g., first try 5 seconds, if fails again, try 10 seconds, etc.).

Thoughts?

**Comment by ksparakis** [comment]
I keep running into this issue, and would really like to see it fixed. I have my email check set to 3 seconds, so when I log out I get a new login page every 3 seconds. This is ridiculous as it doesnt allow me to login from new pages being created.

New pages created first of all should not be focused/ there should not be a new page created to login. We should just get a red icon that we click to login.

**Comment by joeyespo** [comment]
I was able to reproduce. Looks like every "inbox check" request was opening a new login page when it responds with 401. I just fixed this to open exactly once each time you get logged out in 98deee96b4700276f6a577cbc64d1484da2de6be.

**Comment by joeyespo** [comment]
Just released v4.3.0. Feel free to re-open if you see this happen again.

Thanks for the issue, @pydolan!
