### ISSUE TITLE
Fail to Login

### ISSUE THREAD

**Issue by GhaleonZ** [joeyespo/inbox-by-gmail-checker#32]
This happens constantly and repeatedly today. The app seems to have an intense amount of trouble staying connected with Gmail. And no matter what I can no longer sign into any of the Gmail accounts I tried this with. Every one instantly fails to login and it's getting very annoying.

**Comment by joeyespo** [comment]
Sorry that you had to experience this. Merging this with #12, where I go into detail about the problem.
