### ISSUE TITLE
Clicking the Inbox icon opens a second Inbox tab when many tabs are opened

### ISSUE THREAD

**Issue by Najki** [joeyespo/inbox-by-gmail-checker#34]
Tested in Chrome 59.0.3071.115 on Windows.

I now have 22 tabs opened (yeah, I know...) and 3 of them are pinned. The fourth one is Inbox. When the active tab is the Inbox tab then clicking on the plugin's Inbox icon does nothing (beside updating the number of unread messages) which is good. But when any other tab is the active one and I click on the plugin's Inbox icon then a second Inbox tab is opened. It should take me back to the one that already is opened.

Not sure if this is indeed related to the number of opened tabs cause I can't close them right now (doing some research). I will check on it later.

**Comment by joeyespo** [comment]
Hmm, I can't seem to reproduce.

Is this option checked for you?

![image](https://user-images.githubusercontent.com/634573/27969573-5b998b92-6319-11e7-90e7-69ff43b1f7bd.png)

If so, try this
1. Uncheck it
2. Save
3. Close the options page
4. Open the options page again
5. Check it again
6. Save

This option requests more permissions, so perhaps the upgrade didn't do this correctly now that the extension requires fewer permissions.

**Comment by Najki** [comment]
Damn. I need to check this again. It happened at work and now I'm home, so I'll check it on monday. But on my home computer I indeed have this unchecked (but I don't remember that it would happen to me even once at home, it happened at work only).

I'll let you know on monday.

**Comment by Najki** [comment]
Hey, it works now :+1:. I think it was due to these options getting unchecked in some weird circumstances. Now it works as expected and the options are ok.

**Comment by joeyespo** [comment]
Awesome! Thanks for reporting back 😃
