### ISSUE TITLE
Change icon on quiet hours mode

### ISSUE THREAD

**Issue by orschiro** [joeyespo/inbox-by-gmail-checker#9]
As requested by @joeyespo, a separate issue for the following request:

> During quiet hours I find it too tempting and distracting to see the number of unread messages that were fetched during the last non-quiet session. 
> Would it be possible to remove the number count during quiet hours or display something instead, e.g. a `Q` for quiet or `Szz...` for sleeping? :)

Reference: https://github.com/joeyespo/inbox-by-gmail-checker/issues/7#issuecomment-172046597

**Comment by joeyespo** [comment]
After tinkering with what the caption should be, I'm realizing that it's still a badge that triggers the urge to click the button. (Also, using Unicode to show [a clock](http://www.fileformat.info/info/unicode/char/23f0/index.htm) icon [won't work](http://stackoverflow.com/questions/31498506/how-to-set-unicode-character-as-badge-text-on-browser-action-in-chrome-extension).)

What do you think of using another color?

![quiet mode icon](https://cloud.githubusercontent.com/assets/634573/12370450/719542c0-bbdf-11e5-836b-9dd8d454bbd3.png)

**Comment by orschiro** [comment]
@joeyespo,

Cool idea! Maybe a grey colour though?

~Robert

**Comment by joeyespo** [comment]
Thanks! I would have chosen grey, but that's already used as the "could not connect" color:

![inbox_not_logged_in](https://cloud.githubusercontent.com/assets/634573/12372559/27cfaa80-bc2b-11e5-8a2f-8d32689ffb8b.png)

**Comment by orschiro** [comment]
I think yellow is fine then.

Otherwise, people recommend [purple](https://answers.yahoo.com/question/index?qid=20080828123000AAc54zM) as a calm, quiet colour. :)

~Robert

**Comment by joeyespo** [comment]
Fixed with 90d9767837f82def4411b512aa422a8137672583. The "quiet mode" icon will now look like this ![inbox_quiet](https://cloud.githubusercontent.com/assets/634573/12865104/4c6a8eb8-cc71-11e5-8b6a-95274c07b530.png) (slightly more orange than the above screenshot, which matches the Snooze color in Inbox better).

Thanks for the idea, @orschiro!

**Comment by orschiro** [comment]
> Thanks for the idea, @orschiro!

Thank you for implementing it and being supportive! :+1: 

~Robert
